-- Generated by Matugen
return {
    colors = {
        primary = "{{colors.primary.default.hex}}",
        secondary = "{{colors.secondary.default.hex}}",
        surface = "{{colors.surface.default.hex}}",
        text = "{{colors.on_surface.default.hex}}",
    }
}
